{"kind":"symbol","identifier":{"url":"doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify\/CameraFrame\/buffer","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"The raw camera buffer containing the image data"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/blinkidverify\/cameraframe\/buffer"]}],"metadata":{"roleHeading":"Instance Property","title":"buffer","externalID":"s:13BlinkIDVerify11CameraFrameV6bufferSo21MBSampleBufferWrapperCvp","symbolKind":"property","role":"symbol","modules":[{"name":"BlinkIDVerify"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"buffer","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MBSampleBufferWrapper","preciseIdentifier":"c:objc(cs)MBSampleBufferWrapper"}]},"hierarchy":{"paths":[["doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify","doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify\/CameraFrame"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"buffer"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBSampleBufferWrapper","kind":"typeIdentifier","text":"MBSampleBufferWrapper","identifier":"doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify\/MBSampleBufferWrapper"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"references":{"doc://com.microblink.BlinkIDVerify/documentation/BlinkIDVerify/CameraFrame/buffer":{"title":"buffer","url":"\/documentation\/blinkidverify\/cameraframe\/buffer","identifier":"doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify\/CameraFrame\/buffer","abstract":[{"type":"text","text":"The raw camera buffer containing the image data"}],"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"buffer"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBSampleBufferWrapper","text":"MBSampleBufferWrapper","kind":"typeIdentifier"}],"role":"symbol","type":"topic"},"doc://com.microblink.BlinkIDVerify/documentation/BlinkIDVerify/CameraFrame":{"navigatorTitle":[{"text":"CameraFrame","kind":"identifier"}],"title":"CameraFrame","url":"\/documentation\/blinkidverify\/cameraframe","identifier":"doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify\/CameraFrame","abstract":[{"type":"text","text":"Represents a complete camera frame with its associated metadata."}],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraFrame","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://com.microblink.BlinkIDVerify/documentation/BlinkIDVerify":{"kind":"symbol","title":"BlinkIDVerify","url":"\/documentation\/blinkidverify","role":"collection","abstract":[],"identifier":"doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify","type":"topic"},"doc://com.microblink.BlinkIDVerify/documentation/BlinkIDVerify/MBSampleBufferWrapper":{"title":"MBSampleBufferWrapper","role":"symbol","url":"\/documentation\/blinkidverify\/mbsamplebufferwrapper","kind":"symbol","abstract":[{"type":"text","text":"A wrapper class for CMSampleBufferRef that provides proper memory management and ABI stability."}],"identifier":"doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify\/MBSampleBufferWrapper","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MBSampleBufferWrapper","kind":"identifier"}],"navigatorTitle":[{"text":"MBSampleBufferWrapper","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.microblink.BlinkIDVerify~1documentation~1BlinkIDVerify~1MBSampleBufferWrapper\/title","value":"MBSampleBufferWrapper"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.BlinkIDVerify~1documentation~1BlinkIDVerify~1MBSampleBufferWrapper\/fragments","value":[{"text":"MBSampleBufferWrapper","kind":"identifier"}]},{"value":[{"text":"MBSampleBufferWrapper","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.microblink.BlinkIDVerify~1documentation~1BlinkIDVerify~1MBSampleBufferWrapper\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}