{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"buffer"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBSampleBufferWrapper","identifier":"doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify\/MBSampleBufferWrapper","text":"MBSampleBufferWrapper"},{"kind":"text","text":", "},{"text":"roi","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"RegionOfInterest","identifier":"doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify\/RegionOfInterest","preciseIdentifier":"s:13BlinkIDVerify16RegionOfInterestV"},{"text":" = RegionOfInterest(), ","kind":"text"},{"kind":"externalParam","text":"orientation"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify\/CameraFrameVideoOrientation","kind":"typeIdentifier","preciseIdentifier":"s:13BlinkIDVerify27CameraFrameVideoOrientationO","text":"CameraFrameVideoOrientation"},{"text":" = .portrait)","kind":"text"}],"platforms":["iOS"]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The wrapped sample buffer containing the image data"}],"type":"paragraph"}],"name":"buffer"},{"content":[{"inlineContent":[{"type":"text","text":"The region of interest within the frame. Defaults to full frame"}],"type":"paragraph"}],"name":"roi"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The orientation of the camera. Defaults to portrait","type":"text"}]}],"name":"orientation"}],"kind":"parameters"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"symbolKind":"init","modules":[{"name":"BlinkIDVerify"}],"role":"symbol","roleHeading":"Initializer","externalID":"s:13BlinkIDVerify11CameraFrameV6buffer3roi11orientationACSo21MBSampleBufferWrapperC_AA16RegionOfInterestVAA0cD16VideoOrientationOtcfc","title":"init(buffer:roi:orientation:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"buffer","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MBSampleBufferWrapper","text":"MBSampleBufferWrapper","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"roi","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:13BlinkIDVerify16RegionOfInterestV","kind":"typeIdentifier","text":"RegionOfInterest"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"orientation"},{"kind":"text","text":": "},{"text":"CameraFrameVideoOrientation","kind":"typeIdentifier","preciseIdentifier":"s:13BlinkIDVerify27CameraFrameVideoOrientationO"},{"kind":"text","text":")"}]},"hierarchy":{"paths":[["doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify","doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify\/CameraFrame"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify\/CameraFrame\/init(buffer:roi:orientation:)"},"kind":"symbol","abstract":[{"text":"Creates a new camera frame instance.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/blinkidverify\/cameraframe\/init(buffer:roi:orientation:)"]}],"sections":[],"references":{"doc://com.microblink.BlinkIDVerify/documentation/BlinkIDVerify":{"abstract":[],"type":"topic","kind":"symbol","role":"collection","url":"\/documentation\/blinkidverify","title":"BlinkIDVerify","identifier":"doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify"},"doc://com.microblink.BlinkIDVerify/documentation/BlinkIDVerify/CameraFrameVideoOrientation":{"url":"\/documentation\/blinkidverify\/cameraframevideoorientation","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraFrameVideoOrientation"}],"kind":"symbol","abstract":[{"type":"text","text":"Represents the video orientation of a camera frame."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraFrameVideoOrientation"}],"identifier":"doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify\/CameraFrameVideoOrientation","role":"symbol","title":"CameraFrameVideoOrientation"},"doc://com.microblink.BlinkIDVerify/documentation/BlinkIDVerify/CameraFrame":{"title":"CameraFrame","url":"\/documentation\/blinkidverify\/cameraframe","kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Represents a complete camera frame with its associated metadata."}],"identifier":"doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify\/CameraFrame","navigatorTitle":[{"text":"CameraFrame","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraFrame","kind":"identifier"}]},"doc://com.microblink.BlinkIDVerify/documentation/BlinkIDVerify/CameraFrame/init(buffer:roi:orientation:)":{"identifier":"doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify\/CameraFrame\/init(buffer:roi:orientation:)","kind":"symbol","type":"topic","abstract":[{"text":"Creates a new camera frame instance.","type":"text"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"buffer"},{"kind":"text","text":": "},{"text":"MBSampleBufferWrapper","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBSampleBufferWrapper"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"roi"},{"kind":"text","text":": "},{"text":"RegionOfInterest","kind":"typeIdentifier","preciseIdentifier":"s:13BlinkIDVerify16RegionOfInterestV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"orientation"},{"text":": ","kind":"text"},{"text":"CameraFrameVideoOrientation","kind":"typeIdentifier","preciseIdentifier":"s:13BlinkIDVerify27CameraFrameVideoOrientationO"},{"text":")","kind":"text"}],"url":"\/documentation\/blinkidverify\/cameraframe\/init(buffer:roi:orientation:)","title":"init(buffer:roi:orientation:)","role":"symbol"},"doc://com.microblink.BlinkIDVerify/documentation/BlinkIDVerify/MBSampleBufferWrapper":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBSampleBufferWrapper"}],"navigatorTitle":[{"kind":"identifier","text":"MBSampleBufferWrapper"}],"url":"\/documentation\/blinkidverify\/mbsamplebufferwrapper","title":"MBSampleBufferWrapper","identifier":"doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify\/MBSampleBufferWrapper","abstract":[{"text":"A wrapper class for CMSampleBufferRef that provides proper memory management and ABI stability.","type":"text"}],"role":"symbol","kind":"symbol","type":"topic"},"doc://com.microblink.BlinkIDVerify/documentation/BlinkIDVerify/RegionOfInterest":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"RegionOfInterest"}],"kind":"symbol","role":"symbol","abstract":[{"text":"An object that represents camera’s region of interest of frame analyzer.","type":"text"}],"identifier":"doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify\/RegionOfInterest","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RegionOfInterest","kind":"identifier"}],"title":"RegionOfInterest","url":"\/documentation\/blinkidverify\/regionofinterest"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.microblink.BlinkIDVerify~1documentation~1BlinkIDVerify~1MBSampleBufferWrapper\/title","op":"replace","value":"MBSampleBufferWrapper"},{"path":"\/references\/doc:~1~1com.microblink.BlinkIDVerify~1documentation~1BlinkIDVerify~1MBSampleBufferWrapper\/fragments","value":[{"text":"MBSampleBufferWrapper","kind":"identifier"}],"op":"replace"},{"value":[{"text":"MBSampleBufferWrapper","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.microblink.BlinkIDVerify~1documentation~1BlinkIDVerify~1MBSampleBufferWrapper\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}