{"identifier":{"url":"doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify\/MBSampleBufferWrapper\/buffer","interfaceLanguage":"swift"},"metadata":{"title":"buffer","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","modules":[{"name":"BlinkIDVerify"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"buffer","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CMSampleBufferRef","text":"CMSampleBuffer","kind":"typeIdentifier"}],"externalID":"c:objc(cs)MBSampleBufferWrapper(py)buffer","navigatorTitle":[{"text":"buffer","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/blinkidverify\/mbsamplebufferwrapper\/buffer"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/blinkidverify\/mbsamplebufferwrapper\/buffer"]}],"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"buffer"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CMSampleBufferRef","text":"CMSampleBuffer"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify","doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify\/MBSampleBufferWrapper"]]},"references":{"doc://com.microblink.BlinkIDVerify/documentation/BlinkIDVerify/MBSampleBufferWrapper":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBSampleBufferWrapper"}],"navigatorTitle":[{"kind":"identifier","text":"MBSampleBufferWrapper"}],"url":"\/documentation\/blinkidverify\/mbsamplebufferwrapper","title":"MBSampleBufferWrapper","identifier":"doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify\/MBSampleBufferWrapper","abstract":[{"text":"A wrapper class for CMSampleBufferRef that provides proper memory management and ABI stability.","type":"text"}],"role":"symbol","kind":"symbol","type":"topic"},"doc://com.microblink.BlinkIDVerify/documentation/BlinkIDVerify/MBSampleBufferWrapper/buffer":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"buffer"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@CMSampleBufferRef","text":"CMSampleBuffer","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify\/MBSampleBufferWrapper\/buffer","title":"buffer","type":"topic","kind":"symbol","url":"\/documentation\/blinkidverify\/mbsamplebufferwrapper\/buffer","navigatorTitle":[{"kind":"identifier","text":"buffer"}],"abstract":[]},"doc://com.microblink.BlinkIDVerify/documentation/BlinkIDVerify":{"abstract":[],"type":"topic","kind":"symbol","role":"collection","url":"\/documentation\/blinkidverify","title":"BlinkIDVerify","identifier":"doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"buffer","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"buffer"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@S@opaqueCMSampleBuffer","text":"opaqueCMSampleBuffer","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"buffer","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"value":"MBSampleBufferWrapper","op":"replace","path":"\/references\/doc:~1~1com.microblink.BlinkIDVerify~1documentation~1BlinkIDVerify~1MBSampleBufferWrapper\/title"},{"value":[{"kind":"identifier","text":"MBSampleBufferWrapper"}],"op":"replace","path":"\/references\/doc:~1~1com.microblink.BlinkIDVerify~1documentation~1BlinkIDVerify~1MBSampleBufferWrapper\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.BlinkIDVerify~1documentation~1BlinkIDVerify~1MBSampleBufferWrapper\/navigatorTitle","value":[{"text":"MBSampleBufferWrapper","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.microblink.BlinkIDVerify~1documentation~1BlinkIDVerify~1MBSampleBufferWrapper~1buffer\/title","op":"replace","value":"buffer"},{"path":"\/references\/doc:~1~1com.microblink.BlinkIDVerify~1documentation~1BlinkIDVerify~1MBSampleBufferWrapper~1buffer\/fragments","op":"replace","value":[{"text":"buffer","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}