{"abstract":[{"text":"Inherited from ","type":"text"},{"code":"MBSampleBufferWrapper.init(CMSampleBuffer:)","type":"codeVoice"},{"text":".","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/blinkidverify\/mbsamplebufferwrapper\/init(cmsamplebuffer:)-2z7eq"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify","doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify\/MBSampleBufferWrapper"]]},"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"CMSampleBuffer"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CMSampleBufferRef","text":"CMSampleBuffer","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"init(CMSampleBuffer:)","roleHeading":"Initializer","role":"symbol","modules":[{"name":"BlinkIDVerify"}],"platforms":[],"externalID":"c:objc(cs)MBSampleBufferWrapper(im)initWithCMSampleBuffer:::SYNTHESIZED::c:objc(cs)MBSampleBufferWrapper","symbolKind":"init"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify\/MBSampleBufferWrapper\/init(CMSampleBuffer:)-2z7eq"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"CMSampleBuffer"},{"text":" ","kind":"text"},{"text":"cmSampleBuffer","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"CMSampleBuffer","kind":"typeIdentifier","preciseIdentifier":"c:@T@CMSampleBufferRef"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://com.microblink.BlinkIDVerify/documentation/BlinkIDVerify/MBSampleBufferWrapper":{"title":"MBSampleBufferWrapper","role":"symbol","url":"\/documentation\/blinkidverify\/mbsamplebufferwrapper","kind":"symbol","abstract":[{"type":"text","text":"A wrapper class for CMSampleBufferRef that provides proper memory management and ABI stability."}],"identifier":"doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify\/MBSampleBufferWrapper","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MBSampleBufferWrapper","kind":"identifier"}],"navigatorTitle":[{"text":"MBSampleBufferWrapper","kind":"identifier"}]},"doc://com.microblink.BlinkIDVerify/documentation/BlinkIDVerify/MBSampleBufferWrapper/init(CMSampleBuffer:)-2z7eq":{"identifier":"doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify\/MBSampleBufferWrapper\/init(CMSampleBuffer:)-2z7eq","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CMSampleBuffer","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CMSampleBufferRef","text":"CMSampleBuffer","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/blinkidverify\/mbsamplebufferwrapper\/init(cmsamplebuffer:)-2z7eq","kind":"symbol","abstract":[],"title":"init(CMSampleBuffer:)","role":"symbol"},"doc://com.microblink.BlinkIDVerify/documentation/BlinkIDVerify":{"kind":"symbol","title":"BlinkIDVerify","url":"\/documentation\/blinkidverify","role":"collection","abstract":[],"identifier":"doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"MBSampleBufferWrapper","path":"\/references\/doc:~1~1com.microblink.BlinkIDVerify~1documentation~1BlinkIDVerify~1MBSampleBufferWrapper\/title"},{"value":[{"text":"MBSampleBufferWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1com.microblink.BlinkIDVerify~1documentation~1BlinkIDVerify~1MBSampleBufferWrapper\/fragments","op":"replace"},{"op":"replace","value":[{"text":"MBSampleBufferWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1com.microblink.BlinkIDVerify~1documentation~1BlinkIDVerify~1MBSampleBufferWrapper\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}