{"variants":[{"paths":["\/documentation\/blinkidverify\/mbsamplebufferwrapper\/init(cmsamplebuffer:)-9cg9"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/blinkidverify\/mbsamplebufferwrapper\/init(cmsamplebuffer:)-9cg9"]}],"hierarchy":{"paths":[["doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify","doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify\/MBSampleBufferWrapper"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify\/MBSampleBufferWrapper\/init(cmSampleBuffer:)-9cg9"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"cmSampleBuffer","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CMSampleBufferRef","text":"CMSampleBuffer"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"modules":[{"name":"BlinkIDVerify"}],"externalID":"c:objc(cs)MBSampleBufferWrapper(im)initWithCMSampleBuffer:","title":"init(cmSampleBuffer:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cmSampleBuffer"},{"kind":"text","text":": "},{"text":"CMSampleBuffer","kind":"typeIdentifier","preciseIdentifier":"c:@T@CMSampleBufferRef"},{"text":")","kind":"text"}],"role":"symbol","roleHeading":"Initializer","symbolKind":"init","navigatorTitle":[{"text":"initWithCMSampleBuffer:","kind":"identifier"}]},"sections":[],"references":{"doc://com.microblink.BlinkIDVerify/documentation/BlinkIDVerify/MBSampleBufferWrapper":{"title":"MBSampleBufferWrapper","role":"symbol","url":"\/documentation\/blinkidverify\/mbsamplebufferwrapper","kind":"symbol","abstract":[{"type":"text","text":"A wrapper class for CMSampleBufferRef that provides proper memory management and ABI stability."}],"identifier":"doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify\/MBSampleBufferWrapper","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MBSampleBufferWrapper","kind":"identifier"}],"navigatorTitle":[{"text":"MBSampleBufferWrapper","kind":"identifier"}]},"doc://com.microblink.BlinkIDVerify/documentation/BlinkIDVerify/MBSampleBufferWrapper/init(cmSampleBuffer:)-9cg9":{"type":"topic","abstract":[],"title":"init(cmSampleBuffer:)","identifier":"doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify\/MBSampleBufferWrapper\/init(cmSampleBuffer:)-9cg9","url":"\/documentation\/blinkidverify\/mbsamplebufferwrapper\/init(cmsamplebuffer:)-9cg9","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cmSampleBuffer","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CMSampleBufferRef","text":"CMSampleBuffer"},{"kind":"text","text":")"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithCMSampleBuffer:"}]},"doc://com.microblink.BlinkIDVerify/documentation/BlinkIDVerify":{"kind":"symbol","title":"BlinkIDVerify","url":"\/documentation\/blinkidverify","role":"collection","abstract":[],"identifier":"doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithCMSampleBuffer:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithCMSampleBuffer:","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithCMSampleBuffer:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"opaqueCMSampleBuffer","preciseIdentifier":"c:@S@opaqueCMSampleBuffer"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cmSampleBuffer"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.BlinkIDVerify~1documentation~1BlinkIDVerify~1MBSampleBufferWrapper\/title","value":"MBSampleBufferWrapper"},{"path":"\/references\/doc:~1~1com.microblink.BlinkIDVerify~1documentation~1BlinkIDVerify~1MBSampleBufferWrapper\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBSampleBufferWrapper"}]},{"path":"\/references\/doc:~1~1com.microblink.BlinkIDVerify~1documentation~1BlinkIDVerify~1MBSampleBufferWrapper\/navigatorTitle","op":"replace","value":[{"text":"MBSampleBufferWrapper","kind":"identifier"}]},{"value":"initWithCMSampleBuffer:","op":"replace","path":"\/references\/doc:~1~1com.microblink.BlinkIDVerify~1documentation~1BlinkIDVerify~1MBSampleBufferWrapper~1init(cmSampleBuffer:)-9cg9\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.BlinkIDVerify~1documentation~1BlinkIDVerify~1MBSampleBufferWrapper~1init(cmSampleBuffer:)-9cg9\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithCMSampleBuffer:","kind":"identifier"}]}]}]}