{"metadata":{"navigatorTitle":[{"text":"$s13BlinkIDVerify11CameraFrameV6bufferSo21MBSampleBufferWrapperCvg","kind":"identifier"}],"fragments":[{"kind":"identifier","text":"$s13BlinkIDVerify11CameraFrameV6bufferSo21MBSampleBufferWrapperCvg"}],"externalID":"c:@F@$s13BlinkIDVerify11CameraFrameV6bufferSo21MBSampleBufferWrapperCvg","roleHeading":"Function","title":"$s13BlinkIDVerify11CameraFrameV6bufferSo21MBSampleBufferWrapperCvg","role":"symbol","symbolKind":"func","modules":[{"name":"BlinkIDVerify"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBSampleBufferWrapper","identifier":"doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify\/MBSampleBufferWrapper","text":"MBSampleBufferWrapper"},{"text":" * ","kind":"text"},{"text":"$s13BlinkIDVerify11CameraFrameV6bufferSo21MBSampleBufferWrapperCvg","kind":"identifier"},{"kind":"text","text":"("},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":" * "},{"text":"_self","kind":"internalParam"},{"text":");","kind":"text"}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify"]]},"identifier":{"url":"doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify\/$s13BlinkIDVerify11CameraFrameV6bufferSo21MBSampleBufferWrapperCvg","interfaceLanguage":"occ"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/blinkidverify\/$s13blinkidverify11cameraframev6bufferso21mbsamplebufferwrappercvg"]}],"kind":"symbol","references":{"doc://com.microblink.BlinkIDVerify/documentation/BlinkIDVerify/$s13BlinkIDVerify11CameraFrameV6bufferSo21MBSampleBufferWrapperCvg":{"fragments":[{"kind":"identifier","text":"$s13BlinkIDVerify11CameraFrameV6bufferSo21MBSampleBufferWrapperCvg"}],"kind":"symbol","url":"\/documentation\/blinkidverify\/$s13blinkidverify11cameraframev6bufferso21mbsamplebufferwrappercvg","role":"symbol","type":"topic","title":"$s13BlinkIDVerify11CameraFrameV6bufferSo21MBSampleBufferWrapperCvg","abstract":[],"identifier":"doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify\/$s13BlinkIDVerify11CameraFrameV6bufferSo21MBSampleBufferWrapperCvg"},"doc://com.microblink.BlinkIDVerify/documentation/BlinkIDVerify":{"abstract":[],"type":"topic","kind":"symbol","role":"collection","url":"\/documentation\/blinkidverify","title":"BlinkIDVerify","identifier":"doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify"},"doc://com.microblink.BlinkIDVerify/documentation/BlinkIDVerify/MBSampleBufferWrapper":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBSampleBufferWrapper"}],"navigatorTitle":[{"kind":"identifier","text":"MBSampleBufferWrapper"}],"url":"\/documentation\/blinkidverify\/mbsamplebufferwrapper","title":"MBSampleBufferWrapper","identifier":"doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify\/MBSampleBufferWrapper","abstract":[{"text":"A wrapper class for CMSampleBufferRef that provides proper memory management and ABI stability.","type":"text"}],"role":"symbol","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.microblink.BlinkIDVerify~1documentation~1BlinkIDVerify~1MBSampleBufferWrapper\/title","value":"MBSampleBufferWrapper"},{"path":"\/references\/doc:~1~1com.microblink.BlinkIDVerify~1documentation~1BlinkIDVerify~1MBSampleBufferWrapper\/fragments","value":[{"kind":"identifier","text":"MBSampleBufferWrapper"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.microblink.BlinkIDVerify~1documentation~1BlinkIDVerify~1MBSampleBufferWrapper\/navigatorTitle","value":[{"text":"MBSampleBufferWrapper","kind":"identifier"}],"op":"replace"}]}]}