{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","metadata":{"role":"symbol","fragments":[{"text":"$s13BlinkIDVerify11CameraFrameV6buffer3roi11orientationACSo21MBSampleBufferWrapperC_AA16RegionOfInterestVAA0cD16VideoOrientationOtcfC","kind":"identifier"}],"symbolKind":"func","navigatorTitle":[{"kind":"identifier","text":"$s13BlinkIDVerify11CameraFrameV6buffer3roi11orientationACSo21MBSampleBufferWrapperC_AA16RegionOfInterestVAA0cD16VideoOrientationOtcfC"}],"externalID":"c:@F@$s13BlinkIDVerify11CameraFrameV6buffer3roi11orientationACSo21MBSampleBufferWrapperC_AA16RegionOfInterestVAA0cD16VideoOrientationOtcfC","modules":[{"name":"BlinkIDVerify"}],"roleHeading":"Function","title":"$s13BlinkIDVerify11CameraFrameV6buffer3roi11orientationACSo21MBSampleBufferWrapperC_AA16RegionOfInterestVAA0cD16VideoOrientationOtcfC"},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify\/$s13BlinkIDVerify11CameraFrameV6buffer3roi11orientationACSo21MBSampleBufferWrapperC_AA16RegionOfInterestVAA0cD16VideoOrientationOtcfC"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/blinkidverify\/$s13blinkidverify11cameraframev6buffer3roi11orientationacso21mbsamplebufferwrapperc_aa16regionofinterestvaa0cd16videoorientationotcfc"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"extern","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" "},{"text":"$s13BlinkIDVerify11CameraFrameV6buffer3roi11orientationACSo21MBSampleBufferWrapperC_AA16RegionOfInterestVAA0cD16VideoOrientationOtcfC","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"kind":"text","text":", "},{"text":"MBSampleBufferWrapper","preciseIdentifier":"c:objc(cs)MBSampleBufferWrapper","identifier":"doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify\/MBSampleBufferWrapper","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"internalParam","text":"buffer"},{"kind":"text","text":", "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"internalParam","text":"roi"},{"kind":"text","text":", "},{"text":"const","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"orientation","kind":"internalParam"},{"text":");","kind":"text"}]}]}],"references":{"doc://com.microblink.BlinkIDVerify/documentation/BlinkIDVerify/$s13BlinkIDVerify11CameraFrameV6buffer3roi11orientationACSo21MBSampleBufferWrapperC_AA16RegionOfInterestVAA0cD16VideoOrientationOtcfC":{"url":"\/documentation\/blinkidverify\/$s13blinkidverify11cameraframev6buffer3roi11orientationacso21mbsamplebufferwrapperc_aa16regionofinterestvaa0cd16videoorientationotcfc","identifier":"doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify\/$s13BlinkIDVerify11CameraFrameV6buffer3roi11orientationACSo21MBSampleBufferWrapperC_AA16RegionOfInterestVAA0cD16VideoOrientationOtcfC","kind":"symbol","fragments":[{"kind":"identifier","text":"$s13BlinkIDVerify11CameraFrameV6buffer3roi11orientationACSo21MBSampleBufferWrapperC_AA16RegionOfInterestVAA0cD16VideoOrientationOtcfC"}],"role":"symbol","title":"$s13BlinkIDVerify11CameraFrameV6buffer3roi11orientationACSo21MBSampleBufferWrapperC_AA16RegionOfInterestVAA0cD16VideoOrientationOtcfC","abstract":[],"type":"topic"},"doc://com.microblink.BlinkIDVerify/documentation/BlinkIDVerify/MBSampleBufferWrapper":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBSampleBufferWrapper"}],"navigatorTitle":[{"kind":"identifier","text":"MBSampleBufferWrapper"}],"url":"\/documentation\/blinkidverify\/mbsamplebufferwrapper","title":"MBSampleBufferWrapper","identifier":"doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify\/MBSampleBufferWrapper","abstract":[{"text":"A wrapper class for CMSampleBufferRef that provides proper memory management and ABI stability.","type":"text"}],"role":"symbol","kind":"symbol","type":"topic"},"doc://com.microblink.BlinkIDVerify/documentation/BlinkIDVerify":{"abstract":[],"type":"topic","kind":"symbol","role":"collection","url":"\/documentation\/blinkidverify","title":"BlinkIDVerify","identifier":"doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MBSampleBufferWrapper","path":"\/references\/doc:~1~1com.microblink.BlinkIDVerify~1documentation~1BlinkIDVerify~1MBSampleBufferWrapper\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.BlinkIDVerify~1documentation~1BlinkIDVerify~1MBSampleBufferWrapper\/fragments","value":[{"text":"MBSampleBufferWrapper","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.microblink.BlinkIDVerify~1documentation~1BlinkIDVerify~1MBSampleBufferWrapper\/navigatorTitle","value":[{"text":"MBSampleBufferWrapper","kind":"identifier"}],"op":"replace"}]}]}