{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify\/MBSampleBufferWrapper"},"abstract":[{"text":"A wrapper class for CMSampleBufferRef that provides proper memory management and ABI stability.","type":"text"}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.microblink.BlinkIDVerify\/objc(cs)NSObject"]},{"type":"conformsTo","identifiers":["doc:\/\/com.microblink.BlinkIDVerify\/objc(pl)NSObject","doc:\/\/com.microblink.BlinkIDVerify\/s7CVarArgP","doc:\/\/com.microblink.BlinkIDVerify\/s28CustomDebugStringConvertibleP","doc:\/\/com.microblink.BlinkIDVerify\/s23CustomStringConvertibleP","doc:\/\/com.microblink.BlinkIDVerify\/SQ","doc:\/\/com.microblink.BlinkIDVerify\/SH"],"title":"Conforms To","kind":"relationships"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify"]]},"metadata":{"navigatorTitle":[{"text":"MBSampleBufferWrapper","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MBSampleBufferWrapper","kind":"identifier"}],"title":"MBSampleBufferWrapper","externalID":"c:objc(cs)MBSampleBufferWrapper","modules":[{"name":"BlinkIDVerify"}],"roleHeading":"Class","symbolKind":"class","role":"symbol"},"sections":[],"topicSections":[{"identifiers":["doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify\/MBSampleBufferWrapper\/init(cmSampleBuffer:)-9cg9"],"anchor":"Initializers","generated":true,"title":"Initializers"},{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify\/MBSampleBufferWrapper\/buffer"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBSampleBufferWrapper"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","anchor":"overview","level":2,"text":"Overview"},{"inlineContent":[{"type":"codeVoice","code":"MBSampleBufferWrapper"},{"type":"text","text":" safely encapsulates a Core Media sample buffer, ensuring proper"},{"type":"text","text":" "},{"type":"text","text":"reference counting and memory management while maintaining binary compatibility"},{"text":" ","type":"text"},{"type":"text","text":"across different Swift versions."}],"type":"paragraph"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/blinkidverify\/mbsamplebufferwrapper"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/blinkidverify\/mbsamplebufferwrapper"]}],"references":{"doc://com.microblink.BlinkIDVerify/SQ":{"identifier":"doc:\/\/com.microblink.BlinkIDVerify\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.microblink.BlinkIDVerify/s7CVarArgP":{"identifier":"doc:\/\/com.microblink.BlinkIDVerify\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.microblink.BlinkIDVerify/objc(cs)NSObject":{"identifier":"doc:\/\/com.microblink.BlinkIDVerify\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.microblink.BlinkIDVerify/documentation/BlinkIDVerify/MBSampleBufferWrapper/buffer":{"role":"symbol","url":"\/documentation\/blinkidverify\/mbsamplebufferwrapper\/buffer","kind":"symbol","title":"buffer","navigatorTitle":[{"kind":"identifier","text":"buffer"}],"identifier":"doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify\/MBSampleBufferWrapper\/buffer","type":"topic","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"buffer"},{"kind":"text","text":": "},{"text":"CMSampleBuffer","kind":"typeIdentifier","preciseIdentifier":"c:@T@CMSampleBufferRef"}]},"doc://com.microblink.BlinkIDVerify/documentation/BlinkIDVerify/MBSampleBufferWrapper":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBSampleBufferWrapper"}],"kind":"symbol","title":"MBSampleBufferWrapper","identifier":"doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify\/MBSampleBufferWrapper","type":"topic","role":"symbol","url":"\/documentation\/blinkidverify\/mbsamplebufferwrapper","navigatorTitle":[{"text":"MBSampleBufferWrapper","kind":"identifier"}],"abstract":[{"text":"A wrapper class for CMSampleBufferRef that provides proper memory management and ABI stability.","type":"text"}]},"doc://com.microblink.BlinkIDVerify/documentation/BlinkIDVerify":{"url":"\/documentation\/blinkidverify","type":"topic","role":"collection","title":"BlinkIDVerify","abstract":[],"identifier":"doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify","kind":"symbol"},"doc://com.microblink.BlinkIDVerify/SH":{"identifier":"doc:\/\/com.microblink.BlinkIDVerify\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.microblink.BlinkIDVerify/documentation/BlinkIDVerify/MBSampleBufferWrapper/init(cmSampleBuffer:)-9cg9":{"type":"topic","url":"\/documentation\/blinkidverify\/mbsamplebufferwrapper\/init(cmsamplebuffer:)-9cg9","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithCMSampleBuffer:"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cmSampleBuffer","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CMSampleBufferRef","text":"CMSampleBuffer"},{"text":")","kind":"text"}],"role":"symbol","title":"init(cmSampleBuffer:)","identifier":"doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify\/MBSampleBufferWrapper\/init(cmSampleBuffer:)-9cg9","kind":"symbol"},"doc://com.microblink.BlinkIDVerify/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.microblink.BlinkIDVerify\/s23CustomStringConvertibleP"},"doc://com.microblink.BlinkIDVerify/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.microblink.BlinkIDVerify\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.microblink.BlinkIDVerify/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.microblink.BlinkIDVerify\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"MBSampleBufferWrapper","op":"replace"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"MBSampleBufferWrapper","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"MBSampleBufferWrapper","kind":"identifier"}]},{"value":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify\/MBSampleBufferWrapper\/buffer"],"anchor":"Instance-Properties"},{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/com.microblink.BlinkIDVerify\/documentation\/BlinkIDVerify\/MBSampleBufferWrapper\/init(cmSampleBuffer:)-9cg9"]}],"op":"replace","path":"\/topicSections"},{"value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.microblink.BlinkIDVerify\/objc(cs)NSObject"],"kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBSampleBufferWrapper"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.BlinkIDVerify~1documentation~1BlinkIDVerify~1MBSampleBufferWrapper~1buffer\/title","value":"buffer"},{"op":"replace","value":[{"kind":"identifier","text":"buffer"}],"path":"\/references\/doc:~1~1com.microblink.BlinkIDVerify~1documentation~1BlinkIDVerify~1MBSampleBufferWrapper~1buffer\/fragments"},{"path":"\/references\/doc:~1~1com.microblink.BlinkIDVerify~1documentation~1BlinkIDVerify~1MBSampleBufferWrapper\/title","value":"MBSampleBufferWrapper","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.BlinkIDVerify~1documentation~1BlinkIDVerify~1MBSampleBufferWrapper\/fragments","value":[{"kind":"identifier","text":"MBSampleBufferWrapper"}]},{"op":"replace","value":[{"text":"MBSampleBufferWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1com.microblink.BlinkIDVerify~1documentation~1BlinkIDVerify~1MBSampleBufferWrapper\/navigatorTitle"},{"value":"initWithCMSampleBuffer:","path":"\/references\/doc:~1~1com.microblink.BlinkIDVerify~1documentation~1BlinkIDVerify~1MBSampleBufferWrapper~1init(cmSampleBuffer:)-9cg9\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.microblink.BlinkIDVerify~1documentation~1BlinkIDVerify~1MBSampleBufferWrapper~1init(cmSampleBuffer:)-9cg9\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithCMSampleBuffer:","kind":"identifier"}],"op":"replace"}]}]}